version: '2'

services:
  # PostgreSQL database
  db:
    image: postgres:9.4
    hostname: db
    environment:
      - POSTGRES_USER=bi_us
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db_us_test
    ports:
      - "5432:5432"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - ./code/:/hellofresh
      - ../bi-spark-executables:/hellofresh/bi-spark-executables
      - ../data/test_data/:/data

#    environment:
#      - CONFIG_PATH=scripts/config.yml
